<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DeCuongSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('de_cuongs')->delete();

        DB::table('de_cuongs')->truncate();

        DB::table('de_cuongs')->insert([
            ['ma_mon_hoc' => 'CR 424', 'ten_mon_hoc' => 'Lập Trình Ứng Dụng cho các Thiết Bị Di Động', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 416', 'ten_mon_hoc' => 'Cấu Trúc Dữ Liệu & Giải Thuật Nâng Cao', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'5','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'55','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 434', 'ten_mon_hoc' => 'Công Cụ & P.Pháp Thiết Kế Q.Lý (Phần Mềm)', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 403', 'ten_mon_hoc' => 'Công Nghệ Phần Mềm', 'id_quy_tac' => "[{'math':'15','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'25','name':'Đồ Án Nhóm'},{'math':'30','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 316', 'ten_mon_hoc' => 'Giới Thiệu Cấu Trúc Dữ Liệu & Giải Thuật', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'5','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'55','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 100', 'ten_mon_hoc' => 'Giới Thiệu về Khoa Học Máy Tính', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'15','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'15','name':'Đồ Án Nhóm'},{'math':'40','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 462', 'ten_mon_hoc' => 'Kiểm Thử & Đảm Bảo Chất Lượng Phần Mềm', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 314', 'ten_mon_hoc' => 'Lập Trình C trong Unix/Linux', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 311', 'ten_mon_hoc' => 'Lập Trình Hướng Đối Tượng', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'5','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 414', 'ten_mon_hoc' => 'Lập Trình Winforms: VB.NET / C#.NET', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 464', 'ten_mon_hoc' => 'Lập Trình ứng dụng .NET', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 353', 'ten_mon_hoc' => 'Phân Tích & Thiết Kế Hướng Đối Tượng', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 101', 'ten_mon_hoc' => 'Tin Học Đại Cương', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 201', 'ten_mon_hoc' => 'Tin Học Ứng Dụng', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'5','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 211', 'ten_mon_hoc' => 'Lập Trình Cơ Sở', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'5','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'55','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 301', 'ten_mon_hoc' => 'Cơ Sở Dữ Liệu', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'10','name':'Kiểm Tra Thường Kỳ'},{'math':'5','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 402', 'ten_mon_hoc' => 'Hệ Hỗ Trợ Ra Quyết Định', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'10','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 401', 'ten_mon_hoc' => 'Hệ Quản Trị Cơ Sở Dữ Liệu', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 252', 'ten_mon_hoc' => 'Hệ Thống Thông Tin Kế Toán', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'15','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 251', 'ten_mon_hoc' => 'Hệ Thống Thông Tin Quản Lý', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 384', 'ten_mon_hoc' => 'Kỹ Thuật Thương Mại Điện Tử (ASP.NET)', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'15','name':'Đồ Án Nhóm'},{'math':'40','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 385', 'ten_mon_hoc' => 'Kỹ Thuật Thương Mại Điện Tử', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'15','name':'Đồ Án Nhóm'},{'math':'40','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 303', 'ten_mon_hoc' => 'Phân Tích & Thiết Kế Hệ Thống', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'10','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'15','name':'Đồ Án Nhóm'},{'math':'40','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 433', 'ten_mon_hoc' => 'Phân Tích Thông Tin', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'10','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'15','name':'Đồ Án Nhóm'},{'math':'40','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 432', 'ten_mon_hoc' => 'Quản Trị Dự Án Phần Mềm', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'15','name':'Đồ Án Nhóm'},{'math':'40','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 413', 'ten_mon_hoc' => 'Thiết Kế Cơ Sở Dữ Liệu ERP, CRM, SCM', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'15','name':'Đồ Án Nhóm'},{'math':'40','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'IS 381', 'ten_mon_hoc' => 'Thương Mại Điện Tử', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 417', 'ten_mon_hoc' => 'Trí Tuệ Nhân Tạo (Biểu Diễn & Giải Thuật)', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 226', 'ten_mon_hoc' => 'Hệ Điều Hành Unix / Linux', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'15','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 420', 'ten_mon_hoc' => 'Hệ Phân Tán (J2EE, .NET)', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 252', 'ten_mon_hoc' => 'Mạng Máy Tính', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 372', 'ten_mon_hoc' => 'Quản Trị Mạng', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 421', 'ten_mon_hoc' => 'Thiết Kế Mạng', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CR 250', 'ten_mon_hoc' => 'Nền Tảng Hệ Thống Máy Tính', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'15','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 463', 'ten_mon_hoc' => 'Thiết Kế & Tích Hợp Giao Diện', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'10','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 427', 'ten_mon_hoc' => 'An Ninh Internet', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'15','name':'Kiểm Tra Thường Kỳ'},{'math':'15','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 426', 'ten_mon_hoc' => 'Chiến Tranh Thông Tin', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'15','name':'Kiểm Tra Thường Kỳ'},{'math':'15','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 376', 'ten_mon_hoc' => 'Giới Thiệu An Ninh Mạng', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'15','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 430', 'ten_mon_hoc' => 'Kỹ Nghệ Bảo Mật', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'15','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 429', 'ten_mon_hoc' => 'Phản Ứng Tình Huống Tấn Công Mạng', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'15','name':'Kiểm Tra Thường Kỳ'},{'math':'15','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 428', 'ten_mon_hoc' => 'Tấn Công Mạng', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 223', 'ten_mon_hoc' => 'Mạng Internet & dịch vụ', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'MTH 254', 'ten_mon_hoc' => 'Toán RR và Ứng dụng', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'5','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'55','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'MTH 383', 'ten_mon_hoc' => 'Linear Algebra for Data Science', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'15','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'10','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'55','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'SE 445', 'ten_mon_hoc' => 'Tích Hợp Hệ Thống', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'10','name':'Kiểm Tra Thường Kỳ'},{'math':'15','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'20','name':'Đồ Án Nhóm'},{'math':'35','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'STA 285', 'ten_mon_hoc' => 'Probability Theory, Random Processes and Statistical Inference', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'15','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'55','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 366', 'ten_mon_hoc' => 'L.A.M.P. (Linux, Apache, MySQL, PHP)', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'15','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'15','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'10','name':'Đồ Án Nhóm'},{'math':'45','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 466', 'ten_mon_hoc' => 'Perl & Python', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 297', 'ten_mon_hoc' => 'Đồ Án CDIO', 'id_quy_tac' => "[{'math':'15','name':'Chuyên Cần'},{'math':'5','name':'Phát Biểu & Thảo Luận'},{'math':'15','name':'Kiểm Tra Thường Kỳ'},{'math':'10','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'25','name':'Đồ Án Nhóm'},{'math':'30','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 347', 'ten_mon_hoc' => 'Đồ Án CDIO', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'100','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 397', 'ten_mon_hoc' => 'Đồ Án CDIO', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'100','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 447', 'ten_mon_hoc' => 'Đồ Án CDIO', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'100','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 446', 'ten_mon_hoc' => 'Đồ Án Chuyên Ngành: Kỹ Thuật Mạng', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'100','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 345', 'ten_mon_hoc' => 'Đồ Án C.Ngành: C.Nghệ Phần Mềm cho C.Đẳng', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'100','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 445', 'ten_mon_hoc' => 'Đồ Án Chuyên Ngành: Tích Hợp Hệ Thống (COTS)', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'100','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'CS 449', 'ten_mon_hoc' => 'Khóa Luận Tốt Nghiệp', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'100','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'DTE-IT 102', 'ten_mon_hoc' => 'Hướng nghiệp 1', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'10','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'15','name':'Đồ Án Cá Nhân'},{'math':'0','name':'Đồ Án Nhóm'},{'math':'40','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'DTE-IT 152', 'ten_mon_hoc' => 'Hướng nghiệp 2', 'id_quy_tac' => "[{'math':'10','name':'Chuyên Cần'},{'math':'10','name':'Phát Biểu & Thảo Luận'},{'math':'10','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'15','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'15','name':'Đồ Án Nhóm'},{'math':'40','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'DS 371', 'ten_mon_hoc' => 'Machine Learning 2', 'id_quy_tac' => "[{'math':'5','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'20','name':'Thực Hành & Thực Tế'},{'math':'20','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'25','name':'Đồ Án Nhóm'},{'math':'30','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'SE 397', 'ten_mon_hoc' => 'Đồ Án CDIO', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'100','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],
            ['ma_mon_hoc' => 'DS 397', 'ten_mon_hoc' => 'Đồ Án CDIO', 'id_quy_tac' => "[{'math':'0','name':'Chuyên Cần'},{'math':'0','name':'Phát Biểu & Thảo Luận'},{'math':'0','name':'Kiểm Tra Thường Kỳ'},{'math':'0','name':'Bày Tập Về Nhà'},{'math':'0','name':'Thực Hành & Thực Tế'},{'math':'0','name':'Kiểm Tra Giữa Kỳ'},{'math':'0','name':'Đồ Án Cá Nhân'},{'math':'100','name':'Đồ Án Nhóm'},{'math':'0','name':'Kiểm Tra Cuối Kỳ'}]"],

        ]);
    }
}
