<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class HocVienDaDangKySeeder extends Seeder
{
    public function run()
    {
        DB::table('hoc_viens')->delete();

        DB::table('hoc_viens')->truncate();

        DB::table('hoc_viens')->insert([
            [
                'ho_va_ten'             => "Mai Thị Thanh Trúc",
                'ho_lot'                => "Mai Thị Thanh",
                'ten'                   => "Trúc",
                'email'                 => "maithithanhtruc0208@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Trần Công Vinh",
                'ho_lot'                => "Trần Công",
                'ten'                   => "Vinh",
                'email'                 => "vinht43166@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Trần Quốc Luận",
                'ho_lot'                => "Trần Quốc",
                'ten'                   => "Luận",
                'email'                 => "tranquocluan.qna@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Đỗ Thị Yến Vy",
                'ho_lot'                => "Đỗ Thị Yến",
                'ten'                   => "Vy",
                'email'                 => "dothiyenvy2806@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Văn Cầu",
                'ho_lot'                => "Nguyễn Văn",
                'ten'                   => "Cầu",
                'email'                 => "caunguyen.221@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Văn Chương",
                'ho_lot'                => "Nguyễn Văn",
                'ten'                   => "Chương",
                'email'                 => "chuongnguyen19062001@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Mai Thuần",
                'ho_lot'                => "Nguyễn Mai",
                'ten'                   => "Thuần",
                'email'                 => "thuanmai362001@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Huy Hùng",
                'ho_lot'                => "Huy",
                'ten'                   => "Hùng",
                'email'                 => "Huyhung99912@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Lê Công Nguyên",
                'ho_lot'                => "Lê Công",
                'ten'                   => "Nguyên",
                'email'                 => "lecongnguyen9420@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Thanh Đạt",
                'ho_lot'                => "Nguyễn Thanh",
                'ten'                   => "Đạt",
                'email'                 => "nguyenthanhdat631@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Lương Thành Đô",
                'ho_lot'                => "Lương Thành",
                'ten'                   => "Đô",
                'email'                 => "luongthanhdo2018bd@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Phạm Nguyễn Hoàng Huy",
                'ho_lot'                => "Phạm Nguyễn Hoàng",
                'ten'                   => "Huy",
                'email'                 => "huypham.12042002@gmail.com ",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Khôi Nguyên",
                'ho_lot'                => "Nguyễn Khôi",
                'ten'                   => "Nguyên",
                'email'                 => "Pklamaydut99@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Thị Kim Ngân",
                'ho_lot'                => "Nguyễn Thị Kim",
                'ten'                   => "Ngân",
                'email'                 => "kimnganit2001@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Minh",
                'ho_lot'                => "Nguyễn",
                'ten'                   => "Minh",
                'email'                 => "nminh2063@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Đắc Bình Nguyên",
                'ho_lot'                => "Đắc Bình",
                'ten'                   => "Nguyên",
                'email'                 => "dbbnguyen1411@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Duy Phương",
                'ho_lot'                => "Nguyễn Duy",
                'ten'                   => "Phương",
                'email'                 => "duyphuongnguyen467@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Trương Văn Thuận",
                'ho_lot'                => "Trương Văn",
                'ten'                   => "Thuận",
                'email'                 => "thuantruong1596@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Xuân Tuyển",
                'ho_lot'                => "Xuân",
                'ten'                   => "Tuyển",
                'email'                 => "dinhxuantuyen97@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Đặng Công Tùng",
                'ho_lot'                => "Đặng Công",
                'ten'                   => "Tùng",
                'email'                 => "pianlon123@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Huỳnh Nguyễn Trung Quốc",
                'ho_lot'                => "Huỳnh Nguyễn Trung",
                'ten'                   => "Quốc",
                'email'                 => "Quochuynhnguyen123@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Ty",
                'ho_lot'                => "Ty",
                'ten'                   => "Ty",
                'email'                 => "huynhtung1971@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "An Lê",
                'ho_lot'                => "An ",
                'ten'                   => "Lê",
                'email'                 => "anle532211@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Đặng Kiên",
                'ho_lot'                => "Đặng",
                'ten'                   => "Kiên",
                'email'                 => "dangkien5701@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Trương Nam",
                'ho_lot'                => "Nguyễn Trương",
                'ten'                   => "Nam",
                'email'                 => "Nguyentruongnam1512z@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Hưng",
                'ho_lot'                => "Nguyễn",
                'ten'                   => "Hưng",
                'email'                 => "tu.hung1807@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Thanh Thái",
                'ho_lot'                => "Thanh",
                'ten'                   => "Thái",
                'email'                 => "lethanhthai.dtu@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Lê Tú",
                'ho_lot'                => "Lê",
                'ten'                   => "Tú",
                'email'                 => "tusut09022@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Phước Thịnh",
                'ho_lot'                => "Phước",
                'ten'                   => "Thịnh",
                'email'                 => "thinhcon229@gmail.com",
                'so_dien_thoai'         => "0",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 1,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            //khóa 11
            [
                'ho_va_ten'             => "Bùi Văn Tứ",
                'ho_lot'                => "Bùi Văn",
                'ten'                   => "Tứ",
                'email'                 => "buivantu2106@gmail.com",
                'so_dien_thoai'         => "0386452527",
                'facebook'              => "https://www.facebook.com/profile.php?id=100012791490134",
                'mo_ta_trinh_do'        => "sinh viên năm 4 , chuyên ngành big data and machine leaning, yếu về lập trình web và sql ",
                'nguoi_gioi_thieu'      => "Đỗ Thị Yến Vy",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Đỗ Phú Dũng",
                'ho_lot'                => "Đỗ Phú",
                'ten'                   => "Dũng",
                'email'                 => "dophudung2130@gmail.com",
                'so_dien_thoai'         => "0777467902",
                'facebook'              => "https://www.facebook.com/profile.php?id=100031064413242",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Thầy Nguyễn Quốc Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Hồ Thị Thanh Thanh",
                'ho_lot'                => "Hồ Thị Thanh",
                'ten'                   => "Thanh",
                'email'                 => "Thanhthanh186203@gmail.com",
                'so_dien_thoai'         => "0835633234",
                'facebook'              => "https://www.facebook.com/be.athnh.18th6?mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Trần Nguyễn Duy Khánh ",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Huỳnh Công Minh",
                'ho_lot'                => "Huỳnh Công",
                'ten'                   => "Minh",
                'email'                 => "congminh1271995@gmail.com",
                'so_dien_thoai'         => "0705228376",
                'facebook'              => "https://www.facebook.com/minh.huynh.12795/",
                'mo_ta_trinh_do'        => "Có kiến thức cơ bản nhưng còn yếu",
                'nguoi_gioi_thieu'      => "Nguyễn Hưng",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Lê Quốc An",
                'ho_lot'                => "Lê Quốc",
                'ten'                   => "An",
                'email'                 => "atmint76@gmail.com",
                'so_dien_thoai'         => "0866033921",
                'facebook'              => "https://www.facebook.com/profile.php?id=100010432336817&mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Thầy Nguyễn Quốc Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Lê Thanh Bình",
                'ho_lot'                => "Lê Thanh",
                'ten'                   => "Bình",
                'email'                 => "Binhlethanh256@gmail.com",
                'so_dien_thoai'         => "0337893537",
                'facebook'              => "https://www.facebook.com/profile.php?id=100018487413223",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Học trò cũ thầy",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Lê Trọng Huy",
                'ho_lot'                => "Lê Trọng",
                'ten'                   => "Huy",
                'email'                 => "hale.02031982@gmail.com",
                'so_dien_thoai'         => "0983057130",
                'facebook'              => "https://www.facebook.com/hu.le.7712?mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => 'Mạnh',
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Lê Trọng Quỳnh",
                'ho_lot'                => "Lê Trọng",
                'ten'                   => "Quỳnh",
                'email'                 => "quynhle24082001@gmail.com",
                'so_dien_thoai'         => "0777462383",
                'facebook'              => "https://www.facebook.com/profile.php?id=100025893168848",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Em được thầy Long Gửi link Đăng ký trong Lớp đồ án",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Hoài Nam",
                'ho_lot'                => "Nguyễn Hoài",
                'ten'                   => "Nam",
                'email'                 => "namhoai21092017@gmail.com",
                'so_dien_thoai'         => "0839857345",
                'facebook'              => "https://www.facebook.com/Nam.Hoai164?mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Thầy Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Ngọc Hùng",
                'ho_lot'                => "Nguyễn Ngọc",
                'ten'                   => "Hùng",
                'email'                 => "ngochungnguyen2000dhktyddn@gmail.com",
                'so_dien_thoai'         => "0368037472",
                'facebook'              => "https://www.facebook.com/profile.php?id=100009018094598",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Trương Văn Thuận khoá trước",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Ngọc Phúc",
                'ho_lot'                => "Nguyễn Ngọc",
                'ten'                   => "Phúc",
                'email'                 => "Nphucn841@gmail.com",
                'so_dien_thoai'         => "0947282357",
                'facebook'              => "https://www.facebook.com/nphucn841",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Nguyễn Thị Kim Ngân, Mai Thị Thanh Trúc",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Phạm Quốc Hưng",
                'ho_lot'                => "Nguyễn Phạm Quốc",
                'ten'                   => "Hưng",
                'email'                 => "nguyenphamquochung2003@gmail.com",
                'so_dien_thoai'         => "0787794199",
                'facebook'              => "https://www.facebook.com/profile.php?id=100070108275232",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Thầy Nguyễn Quốc Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Phước Thiên Đức",
                'ho_lot'                => "Nguyễn Phước Thiên",
                'ten'                   => "Đức",
                'email'                 => "duc09092001@gmail.com",
                'so_dien_thoai'         => "0935874992",
                'facebook'              => "https://www.facebook.com/bobyuudo?mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => "e bị mất gốc ",
                'nguoi_gioi_thieu'      => "Bạn",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Phương Chinh",
                'ho_lot'                => "Nguyễn Phương",
                'ten'                   => "Chinh",
                'email'                 => "Nhoad123@gmail.com",
                'so_dien_thoai'         => "0383085156",
                'facebook'              => null,
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Quang Huy",
                'ho_lot'                => "Nguyễn Quang",
                'ten'                   => "Huy",
                'email'                 => "nguyenhuyilc2003@gmail.com",
                'so_dien_thoai'         => "0905758603",
                'facebook'              => "https://www.facebook.com/Edramin?mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => "Sinh viên năm 2
                                            +có thể tự debug khi code theo youtobe
                                            +Có thể tự đọc 1 cuốn sách lập trình English
                                            +Đã học qua html,css,php, java và c++",
                'nguoi_gioi_thieu'      => "Nguyễn minh thân",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Quốc Khánh",
                'ho_lot'                => "Nguyễn Quốc",
                'ten'                   => "Khánh",
                'email'                 => "nqk25092002@gmail.com",
                'so_dien_thoai'         => "0356055920",
                'facebook'              => "https://www.facebook.com/profile.php?id=100027113631544&mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Trần Trung Kiên",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Thế Kiên",
                'ho_lot'                => "Nguyễn Thế",
                'ten'                   => "Kiên",
                'email'                 => "Kienthe25@gmail.com",
                'so_dien_thoai'         => "0363361994",
                'facebook'              => "https://www.facebook.com/Ken.oppaaa",
                'mo_ta_trinh_do'        => "Biết chút chút về c++, java ",
                'nguoi_gioi_thieu'      => "Thuận k10",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Thiện Tài",
                'ho_lot'                => "Nguyễn Thiện",
                'ten'                   => "Tài",
                'email'                 => "Lethithuha3100@gmail.com",
                'so_dien_thoai'         => "0947292778",
                'facebook'              => "https://www.facebook.com/nthientaiii?mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Boss Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Trần Văn Hiếu",
                'ho_lot'                => "Nguyễn Trần Văn",
                'ten'                   => "Hiếu",
                'email'                 => "hieukn1@gmail.com",
                'so_dien_thoai'         => "0768581467",
                'facebook'              => "https://www.facebook.com/profile.php?id=100009209753323",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Đô",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Văn Hiếu",
                'ho_lot'                => "Nguyễn Văn",
                'ten'                   => "Hiếu",
                'email'                 => "nguyenvanhieu20020831@gmail.com",
                'so_dien_thoai'         => "0898219157",
                'facebook'              => "https://www.facebook.com/profile.php?id=100027527926628&mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Bạn Thuận khoá 10",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Văn Lành",
                'ho_lot'                => "Nguyễn Văn Lành",
                'ten'                   => "Lành",
                'email'                 => "Lanhnguyen150597@gmail.com",
                'so_dien_thoai'         => "0978318197",
                'facebook'              => "https://www.facebook.com/SihatNguyen?mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Thầy Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Vũ Duy",
                'ho_lot'                => "Nguyễn Vũ",
                'ten'                   => "Duy",
                'email'                 => "vuduy231109@gmail.com",
                'so_dien_thoai'         => "0974181076",
                'facebook'              => "https://www.facebook.com/teo.teoteo.94695?mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Nguyễn Quốc Long ",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Phan Văn Thành Bảo",
                'ho_lot'                => "Phan Văn Thành",
                'ten'                   => "Bảo",
                'email'                 => "phanbao569@gmail.com",
                'so_dien_thoai'         => "0935546152",
                'facebook'              => "https://www.facebook.com/phan.bao.3154?mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "nguyễn ngọc hùng 02/03/00",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Trần Ngọc Tiến",
                'ho_lot'                => "Trần Ngọc",
                'ten'                   => "Tiến",
                'email'                 => "ngoctien10082003@gmail.com",
                'so_dien_thoai'         => "0903526897",
                'facebook'              => "https://www.facebook.com/t.nntien09/",
                'mo_ta_trinh_do'        => "học ổn",
                'nguoi_gioi_thieu'      => "Phùng Văn Mạnh",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Trần Tuấn Kiệt",
                'ho_lot'                => "Trần Tuấn",
                'ten'                   => "Kiệt",
                'email'                 => "hinem04@gmail.com",
                'so_dien_thoai'         => "0905718435",
                'facebook'              => "https://www.facebook.com/profile.php?id=100008496244096&mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Trương Quang Vinh",
                'ho_lot'                => "Trương Quang",
                'ten'                   => "Vinh",
                'email'                 => "Truongquangvinh1999@gmail.com ",
                'so_dien_thoai'         => "0337317578",
                'facebook'              => "https://www.facebook.com/profile.php?id=100011995397763&mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Võ Thị Như Yên",
                'ho_lot'                => "Võ Thị Như",
                'ten'                   => "Yên",
                'email'                 => "vothinhuyen22042003@gmail.com",
                'so_dien_thoai'         => "0848822072",
                'facebook'              => "https://www.facebook.com/yew2204",
                'mo_ta_trinh_do'        => "Sinh viên năm 2 Đại Học Duy Tân. Đã học qua ngôn ngữ C++ và Java nhưng còn rất yếu.
                                            Chưa hiểu rõ về lập trình hướng đối tượng.",
                'nguoi_gioi_thieu'      => "Trần Quốc Luận",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Võ Công Mạnh",
                'ho_lot'                => "Võ Công",
                'ten'                   => "Mạnh",
                'email'                 => "manhvocong@gmail.com",
                'so_dien_thoai'         => "0935977057",
                'facebook'              => "https://www.facebook.com/yew2204",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Thầy LONG",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Cao Trần Yến Nhi",
                'ho_lot'                => "Cao Trần Yến",
                'ten'                   => "Nhi",
                'email'                 => "caonhi15102002@gmai.com",
                'so_dien_thoai'         => "0847770588",
                'facebook'              => "https://www.facebook.com/indixu15112002?mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Thầy Nguyễn Quốc Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Hoàng Phan Văn Ý",
                'ho_lot'                => "Hoàng Phan Văn",
                'ten'                   => "Ý",
                'email'                 => "hpvy.work@gmail.com",
                'so_dien_thoai'         => "0974048425",
                'facebook'              => "https://www.facebook.com/vany.hoang.5855?mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Thầy Long ( class Q )",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],

            [
                'ho_va_ten'             => "Lê Nguyễn Tố Đoan",
                'ho_lot'                => "Lê Nguyễn Tố",
                'ten'                   => "Đoan",
                'email'                 => "lentodoan678@gmail.com",
                'so_dien_thoai'         => "0367050512",
                'facebook'              => "https://www.facebook.com/ToDoan1270?mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => "Em bị mất gốc, mong thầy hướng dẫn ạ.",
                'nguoi_gioi_thieu'      => "Thầy Nguyễn Quốc Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],

            [
                'ho_va_ten'             => "Lê Quang Nhân",
                'ho_lot'                => "Lê Quang",
                'ten'                   => "Nhân",
                'email'                 => "0988122788nhan@gmail.com",
                'so_dien_thoai'         => "0988122788",
                'facebook'              => "https://www.facebook.com/nhanlequang.lequang?mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Nguyễn Ngọc Anh Minh",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Anh Hoàng",
                'ho_lot'                => "Nguyễn Anh",
                'ten'                   => "Hoàng",
                'email'                 => "nguyenanhhoang260703@gmail.com",
                'so_dien_thoai'         => "0353545318",
                'facebook'              => "https://www.facebook.com/profile.php?id=100055141294598",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "thầy Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Quang Lân",
                'ho_lot'                => "Nguyễn Quang",
                'ten'                   => "Lân",
                'email'                 => "okkha1234@gmail.com",
                'so_dien_thoai'         => "0766760405",
                'facebook'              => "https://www.facebook.com/lan003",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Bạn Bè",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Trung Hiếu",
                'ho_lot'                => "Nguyễn Trung",
                'ten'                   => "Hiếu",
                'email'                 => "hieu0916627436@gmail.com",
                'so_dien_thoai'         => "0914804504",
                'facebook'              => "https://www.facebook.com/hieus.trungs.77?mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Lê Công Nguyên",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Phạm Xuân Hải",
                'ho_lot'                => "Phạm Xuân",
                'ten'                   => "Hải",
                'email'                 => "xuanhailmtc@gmail.com",
                'so_dien_thoai'         => "0794907802",
                'facebook'              => "https://www.facebook.com/profile.php?id=100049678271846",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Trần Lê Minh Quân",
                'ho_lot'                => "Trần Lê Minh",
                'ten'                   => "Quân",
                'email'                 => "quantran6102002@gmail.com ",
                'so_dien_thoai'         => "0919586720",
                'facebook'              => "https://www.facebook.com/tran.quanminh.52056?mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => null,
                'nguoi_gioi_thieu'      => "Thầy Long",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Trần Thanh Khoa",
                'ho_lot'                => "Trần Thanh",
                'ten'                   => "Khoa",
                'email'                 => "khoa22012@gmail.com",
                'so_dien_thoai'         => "0777417860",
                'facebook'              => "https://www.facebook.com/profile.php?id=100009094561652&mibextid=LQQJ4d",
                'mo_ta_trinh_do'        => "Em đã mất gốc",
                'nguoi_gioi_thieu'      => null,
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Nguyễn Thành Long",
                'ho_lot'                => "Nguyễn Thành",
                'ten'                   => "Long",
                'email'                 => "Longkolp16@gmail.com",
                'so_dien_thoai'         => "0905807623",
                'facebook'              => "https://www.facebook.com/profile.php?id=100074638756961&mibextid=ZbWKwL",
                'mo_ta_trinh_do'        => "Không biết gì hết",
                'nguoi_gioi_thieu'      => "Qua người quen",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
            [
                'ho_va_ten'             => "Từ Lê Thu Hiền",
                'ho_lot'                => "Từ Lê Thu",
                'ten'                   => "Hiền",
                'email'                 => "tulethuhien@gmail.com",
                'so_dien_thoai'         => "0333314445",
                'facebook'              => "https://www.facebook.com/tulethuhien452001",
                'mo_ta_trinh_do'        => "Em không biết gì hết á thầy😂😂😂",
                'nguoi_gioi_thieu'      => "Anh Đậu Nguyễn Huy Hùng",
                'id_lop_dang_ky'        => 2,
                'password'              => bcrypt(123456),
                'uuid'                  => Str::uuid(),
            ],
        ]);
    }
}
